SportistsApp/Models/ErrorViewModel.cs
using System;

namespace SportistsApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SportistsApp/Models/Sport.cs
namespace SportistsApp.Models
{
    public enum Sport
    {
        Football,
        Handball,
        Basketball,
        TableTennis,
        Swimming,
        Snooker,
        Tennis
    }
}

SportistsApp/Models/Sportists.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SportistsApp.Models
{
    public class Sportists
    {
        
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]

        public string FirstName { get; set; }
        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string LastName { get; set; }
        
        [Required]
        public Sport Sport { get; set; }
        
        [Required]
        public int Ranking { get; set; }

        [Required]
        [DataType(DataType.Url)]
        [Display(Name = "Sportist Link")]
        public string SportistUrl { get; set; }

        [Required]
        [DataType(DataType.ImageUrl)]
        [Display(Name = "Picture")]
        public string ImageUrl { get; set; }
    }
}

SportistsApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SportistsApp.Models;

namespace SportistsApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SportistsApp/Controllers/SportistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportistsApp.Data;
using SportistsApp.Models;

namespace SportistsApp.Controllers
{
    public class SportistsController : Controller
    {
        private readonly SportistsContext _context;

        public SportistsController(SportistsContext context)
        {
            _context = context;
        }

        // GET: Sportists
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentFilter"] = searchString;

            var sportists = from s in _context.Sportists
                         select s;

            if (!string.IsNullOrEmpty(searchString))
            {
                sportists = sportists.Where(s => s.FirstName.Contains(searchString) || s.LastName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    sportists = sportists.OrderByDescending(s => s.FirstName);
                    break;
                default:
                    sportists = sportists.OrderBy(s => s.LastName);
                    break;
            }

            return View(await sportists.AsNoTracking().ToListAsync());
        }

        // GET: Sportists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sportists = await _context.Sportists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sportists == null)
            {
                return NotFound();
            }

            return View(sportists);
        }

        // GET: Sportists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sportists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Sport,Ranking,SportistUrl,ImageUrl")] Sportists sportists)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sportists);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sportists);
        }

        // GET: Sportists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sportists = await _context.Sportists.FindAsync(id);
            if (sportists == null)
            {
                return NotFound();
            }
            return View(sportists);
        }

        // POST: Sportists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Sport,Ranking,SportistUrl,ImageUrl")] Sportists sportists)
        {
            if (id != sportists.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sportists);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SportistsExists(sportists.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sportists);
        }

        // GET: Sportists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sportists = await _context.Sportists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sportists == null)
            {
                return NotFound();
            }

            return View(sportists);
        }

        // POST: Sportists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sportists = await _context.Sportists.FindAsync(id);
            _context.Sportists.Remove(sportists);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SportistsExists(int id)
        {
            return _context.Sportists.Any(e => e.Id == id);
        }
    }
}

SportistsApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SportistsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportistsApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/solid.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Sportists" asp-action="Index">SportistsApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SportistsApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)




</body>
</html>

SportistsApp/Views/Sportists/Create.cshtml
@model SportistsApp.Models.Sportists

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Sportists</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sport" class="control-label"></label>
                <select asp-for="Sport" asp-items="Html.GetEnumSelectList<Sport>()" class="form-control"></select>
                <span asp-validation-for="Sport" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ranking" class="control-label"></label>
                <input asp-for="Ranking" class="form-control" />
                <span asp-validation-for="Ranking" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SportistUrl" class="control-label"></label>
                <input asp-for="SportistUrl" class="form-control" />
                <span asp-validation-for="SportistUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportistsApp/Views/Sportists/Delete.cshtml
@model SportistsApp.Models.Sportists

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sportists</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sport)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sport)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ranking)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ranking)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SportistUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SportistUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SportistsApp/Views/Sportists/Details.cshtml
@model SportistsApp.Models.Sportists

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Sportists</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sport)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sport)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ranking)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ranking)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SportistUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SportistUrl)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SportistsApp/Views/Sportists/Edit.cshtml
@model SportistsApp.Models.Sportists

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Sportists</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sport" class="control-label"></label>
                <select asp-for="Sport" asp-items="Html.GetEnumSelectList<Sport>()"  class="form-control"></select>
                <span asp-validation-for="Sport" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ranking" class="control-label"></label>
                <input asp-for="Ranking" class="form-control" />
                <span asp-validation-for="Ranking" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SportistUrl" class="control-label"></label>
                <input asp-for="SportistUrl" class="form-control" />
                <span asp-validation-for="SportistUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportistsApp/Views/Sportists/Index.cshtml
@model IEnumerable<SportistsApp.Models.Sportists>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@*<form asp-controller="Sportists" asp-action="Index">
    <p>
        <input type="text" placeholder="Search.." name="SearchString">
        <button type="submit"><i class="fa fa-search"></i></button>
    </p>
</form>*@

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <button type="submit"><i class="fa fa-search"></i></button>
            <i class="fas fa-arrow-circle-right"></i>
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sport)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ranking)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SportistUrl)

            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @if (item.ImageUrl != null)
                {
                    <img src="@Url.Content(item.ImageUrl)" alt="Image" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sport)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ranking)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.SportistUrl)*@
                <a href="@item.SportistUrl" target="_blank">@item.FirstName @item.LastName</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>